### ISSUE TITLE
not able to run 

### ISSUE THREAD

**Issue by Alababdiy** [MahdiTa97/my-strapi#3]
i follow step in README but i got this issue : -
```
localhost-2:strapi-custom-slug-master abdo$ npm run develop

> my-project@0.1.0 develop /Users/abdo/Workshop/strapi-custom-slug-master
> strapi develop

You need to run strapi develop in a Strapi project. Make sure you are in the right directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abdo/.npm/_logs/2022-11-22T13_47_32_901Z-debug.log
localhost-2:strapi-custom-slug-master abdo$ strapi develop
You need to run strapi develop in a Strapi project. Make sure you are in the right directory
```

**Comment by Alababdiy** [comment]
@MahdiTa97 Please Help

**Comment by MahdiTa97** [comment]
You have to do `npm install` first.

**Comment by Alababdiy** [comment]
Thanks @MahdiTa97  , But still not working
i tried before with and without sudo 
this error showing 
```
localhost-2:strapi-custom-slug-master abdo$ sudo npm install
npm WARN @emotion/react@11.9.3 requires a peer of react@>=16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fortawesome/react-fontawesome@0.1.18 requires a peer of react@>=16.x but none is installed. You must install peer dependencies yourself.
npm WARN @strapi/design-system@1.1.1 requires a peer of @strapi/icons@^0.0.1-alpha.73 but none is installed. You must install peer dependencies yourself.
npm WARN @webpack-cli/configtest@1.2.0 requires a peer of webpack@4.x.x || 5.x.x but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.2.3 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN css-loader@6.5.1 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN esbuild-loader@2.18.0 requires a peer of webpack@^4.40.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN formik@2.2.9 requires a peer of react@>=16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN grant-koa@5.4.8 requires a peer of koa@>=2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-loader@3.0.1 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@5.5.0 requires a peer of webpack@^5.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN mini-create-react-context@0.4.1 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mini-css-extract-plugin@2.4.4 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN node-polyfill-webpack-plugin@1.1.4 requires a peer of webpack@>=5 but none is installed. You must install peer dependencies yourself.
npm WARN react-copy-to-clipboard@5.1.0 requires a peer of react@^15.3.0 || 16 || 17 || 18 but none is installed. You must install peer dependencies yourself.
npm WARN react-dnd@14.0.5 requires a peer of react@>= 16.14 but none is installed. You must install peer dependencies yourself.
npm WARN react-error-boundary@3.1.1 requires a peer of react@>=16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-helmet@6.1.0 requires a peer of react@>=16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-input-autosize@3.0.0 requires a peer of react@^16.3.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-intl@5.20.2 requires a peer of react@^16.3.0 || 17 but none is installed. You must install peer dependencies yourself.
npm WARN react-query@3.24.3 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-redux@7.2.3 requires a peer of react@^16.8.3 || ^17 but none is installed. You must install peer dependencies yourself.
npm WARN react-router@5.3.3 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
npm WARN react-router-dom@5.2.0 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
npm WARN react-router@5.2.0 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@4.3.1 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@4.3.1 requires a peer of react-dom@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-side-effect@2.1.1 requires a peer of react@^16.3.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.2 requires a peer of react@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@4.4.2 requires a peer of react-dom@>=16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-virtualized@9.22.3 requires a peer of react@^15.3.0 || ^16.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN react-virtualized@9.22.3 requires a peer of react-dom@^15.3.0 || ^16.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN style-loader@3.3.1 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@5.3.3 requires a peer of react@>= 16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@5.3.3 requires a peer of react-dom@>= 16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@5.3.3 requires a peer of react-is@>= 16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@5.3.3 requires a peer of webpack@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-cli@4.9.1 requires a peer of webpack@4.x.x || 5.x.x but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@5.3.3 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@4.7.3 requires a peer of webpack@^4.37.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpackbar@5.0.0-3 requires a peer of webpack@3 || 4 || 5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-64@0.14.44 (node_modules/esbuild-android-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-64@0.14.44: wanted {"os":"android","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.14.44 (node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.14.44: wanted {"os":"android","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.14.44 (node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.14.44: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.14.44 (node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.14.44: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.14.44 (node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.14.44: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.14.44 (node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.14.44: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.14.44 (node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.14.44: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-64@0.14.44 (node_modules/esbuild-linux-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-64@0.14.44: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.14.44 (node_modules/esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.14.44: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.14.44 (node_modules/esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.14.44: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.14.44 (node_modules/esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.14.44: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-riscv64@0.14.44 (node_modules/esbuild-linux-riscv64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-riscv64@0.14.44: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-s390x@0.14.44 (node_modules/esbuild-linux-s390x):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-s390x@0.14.44: wanted {"os":"linux","arch":"s390x"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.14.44 (node_modules/esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.14.44: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.14.44 (node_modules/esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.14.44: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.14.44 (node_modules/esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.14.44: wanted {"os":"sunos","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.14.44 (node_modules/esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.14.44: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.14.44 (node_modules/esbuild-windows-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.14.44: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.14.44 (node_modules/esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.14.44: wanted {"os":"win32","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})

audited 1556 packages in 11.257s

145 packages are looking for funding
  run `npm fund` for details

found 13 vulnerabilities (1 low, 2 moderate, 8 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
localhost-2:strapi-custom-slug-master abdo$ npm run develop

> my-project@0.1.0 develop /Users/abdo/Workshop/strapi-custom-slug-master
> strapi develop

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Cannot find module 'webpack/lib/ModuleFilenameHelpers.js'
Require stack:
- /Users/abdo/Workshop/strapi-custom-slug-master/node_modules/esbuild-loader/dist/minify-plugin.js
- /Users/abdo/Workshop/strapi-custom-slug-master/node_modules/esbuild-loader/dist/index.js
- /Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/admin/webpack.config.js
- /Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/admin/index.js
- /Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/commands/build.js
- /Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/commands/develop.js
- /Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/abdo/Workshop/strapi-custom-slug-master/node_modules/esbuild-loader/dist/minify-plugin.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
localhost-2:strapi-custom-slug-master abdo$ 

```

**Comment by Alababdiy** [comment]
@MahdiTa97 Thanks

here this error showing 

```
localhost-2:strapi-custom-slug-master abdo$ npm run develop

> my-project@0.1.0 develop /Users/abdo/Workshop/strapi-custom-slug-master
> strapi develop

Building your admin UI with development configuration...

✔ Webpack
  Compiled successfully in 21.85s

Admin UI built successfully
[2022-11-24 00:50:42.030] debug: ⛔️ Server wasn't able to start properly.
[2022-11-24 00:50:42.032] error: Middleware "strapi::session": App keys are required. Please set app.keys in config/server.js (ex: keys: ['myKeyA', 'myKeyB'])
Error: Middleware "strapi::session": App keys are required. Please set app.keys in config/server.js (ex: keys: ['myKeyA', 'myKeyB'])
    at instantiateMiddleware (/Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/services/server/middleware.js:13:11)
    at resolveMiddlewares (/Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/services/server/middleware.js:57:18)
    at registerApplicationMiddlewares (/Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/services/server/register-middlewares.js:66:29)
    at async Object.initMiddlewares (/Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/services/server/index.js:102:7)
    at async Strapi.bootstrap (/Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/Strapi.js:461:5)
    at async Strapi.load (/Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/Strapi.js:475:5)
    at async Strapi.start (/Users/abdo/Workshop/strapi-custom-slug-master/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abdo/.npm/_logs/2022-11-23T21_50_42_117Z-debug.log
localhost-2:strapi-custom-slug-master abdo$ 
```

**Comment by Alababdiy** [comment]
Thanks
